//----------------------
// <auto-generated>
//     Generated using the server ThreadboxApi.Application.Common.Reflection.GenerateTypeScriptPermissions()
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export class BoardsPermissions {
  static readonly manage: string = 'Boards.Manage';
}

export class SectionsPermissions {
  static readonly manage: string = 'Sections.Manage';
}

