//----------------------
// <auto-generated>
//     Generated using the server ThreadboxApi.Startup.GeneratePermissionsForClient()
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export class BoardsPermissions {
  static readonly read: string = 'Boards.Read';
  static readonly create: string = 'Boards.Create';
}

